version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    volumes:
      - static_volume:/usr/src/app/static
    depends_on:
      - web
    restart: "on-failure"
  web:
    build: . #build the image for the web service from the dockerfile in parent directory
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --no-input &&
                    gunicorn classyfi.wsgi:application --bind 0.0.0.0:8000"
    volumes:
    # map data and files from parent directory in host to microservice directory in docker containe
      - .:/usr/src/app
      - static_volume:/usr/src/app/static
    env_file:
      - .env
    image: classyfi

    expose:
      - 8000

volumes:
  static_volume:
